#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#minimal_mistakes_skin: "mint"
#remote_theme: wowthemesnet/mediumish-theme-jekyll
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: Davi Saranszky Mesquita
description: 48.112.728/0001-31
